name = "edtdo"
main = "_worker.js"
compatibility_date = "2024-09-23"

[durable_objects]
bindings = [
  { name = "DO", class_name = "EDTDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["EDTDO"]

# [vars]
# UUID = "你的UUID"
# ADMIN = "你的管理员密码"
